### PR TITLE
Support RN 0.40 headers while retaining backwards compatibility.

### PR DESCRIPTION
**Pull request by peacechen**
Use #if to conditionally import React headers.

### CODE REVIEW

**Comment by peacechen** [comment]
@jgrancher 
Are you considering merging this?  Looks like additional native files that have been added which I will also update if you plan to merge.

**Comment by jgrancher** [comment]
Hey @peacechen,
Thanks for pushing it. I've been so keen to merge `v1.0` that I forgot about a possible backward compatibility. Indeed, that would be great if you could update all the files affected to this change, so that people who are still using RN < 0.40 (if any) would be able to use this module.

**Comment by peacechen** [comment]
@jgrancher 
I updated the additional native files.

**Comment by jgrancher** [comment]
@peacechen nice, thanks! Will test it tonight :)

**Pull request merged**
